Rota de busca de usuários
GoogolApp/googol-backend pull request #3
Opened 2018-05-22 13:59 UTC by matheusgmaia

2018-05-24 08:03 UTC, viniagostini requested changes

2018-05-24 08:03 UTC, viniagostini commented on server/user/user.controller.js
> +function search(req, res) {
Lembra que temos que deixar o retorno dessa requisição mais leve? Tem que dar uma modificada nesse cara.

2018-05-24 08:03 UTC, viniagostini commented on server/user/user.controller.js
> +function search(req, res) {
Ahh, e aqui tu pode usar arrow function :slightly_smiling_face:

2018-05-24 08:03 UTC, viniagostini commented on server/user/user.model.js
> +    search(keyword,{ skip = 0, limit = 15 } = {}) {
Cara, a ideia de paginar a busca é boa, mas a acho que vai adicionar um pouco de complexidade a mais no cliente. Tu não acha melhor tirar isso?

2018-05-25 18:30 UTC, matheusgmaia commented on server/user/user.model.js
> +    search(keyword,{ skip = 0, limit = 15 } = {}) {
Vou aumentar o limite então, se por acaso uma busca tiver que retornar mais que 50 então o app ta foda e a gente refatora

2018-05-25 20:41 UTC, merged